name: gobbm-build
on:
  workflow_dispatch:
#   push:
#   pull_request:
#     branches:
#       - main
#     paths-ignore:
#       - '**.md'
jobs:
  build:
    strategy:
      matrix:
        os:
         - ubuntu-latest
        go-version:
         - '1.23'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        id: setup-go
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: |
          go build .
      - name: Test
        run: |
          go test -v -cover .
